package com.company;

public enum Topping {
  TOMATSAUCE, OREGANO, OKSEFARS, KØDSAUCE, SPAGHETTI, PEPPERONI, OST, SKINKE, COCKTAILPØLSER, BACON, LØG, OLIVEN, RØD_PEBER, ANANAS, CHAMPIGNON, KEBAB, CHILI, REJER,
}
